export const CHECKOUT_ACTION_TYPES = {
  SET_PROCESSING: 'checkout/SET_PROCESSING',
  SET_SHOW_STATUS: 'checkout/SET_SHOW_STATUS',
  SET_SUCCESS: 'checkout/SET _SUCCESS',
  SET_CHECKOUT_TOGGLE: 'checkout/SET _CHECKOUT_TOGGLE',
};
