export enum PAYMENT_ACTION_TYPES {
  SET_PROCESSING = 'payment/SET_PROCESSING',
  SET_SHOW_STATUS = 'payment/SET_SHOW_STATUS',
  SET_SUCCESS = 'payment/SET _SUCCESS',
  SET_CHECKOUT_TOGGLE = 'payment/SET _CHECKOUT_TOGGLE',
}
